# Generated by Django 5.1.4 on 2026-09-24 20:48

import apps.whatsapp.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaRapida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atajo', models.SlugField(help_text='Se usa escribiendo /atajo en el chat.', max_length=30, unique=True)),
                ('titulo', models.CharField(max_length=100)),
                ('texto', models.TextField(help_text='Acepta {primer_nombre}, {agente}, {embudo}…')),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['atajo'],
            },
        ),
        migrations.CreateModel(
            name='LineaWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: "Ventas Doctor Flex", "Ventas 2".', max_length=100)),
                ('proveedor', models.CharField(choices=[('evolution', 'Evolution API (QR, WhatsApp común o Business)'), ('meta', 'Meta Cloud API (oficial)'), ('twilio', 'Twilio (oficial vía BSP)')], default='evolution', max_length=15)),
                ('telefono', models.CharField(blank=True, help_text='Número de la línea (informativo).', max_length=20)),
                ('activa', models.BooleanField(default=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('estado', models.CharField(choices=[('conectada', 'Conectada'), ('desconectada', 'Desconectada'), ('conectando', 'Conectando'), ('error', 'Error de credenciales')], default='desconectada', max_length=15)),
                ('estado_detalle', models.CharField(blank=True, max_length=300)),
                ('estado_actualizado_at', models.DateTimeField(blank=True, null=True)),
                ('webhook_key', models.CharField(default=apps.whatsapp.models._nueva_clave, editable=False, max_length=64, unique=True)),
                ('min_segundos_entre_envios', models.PositiveSmallIntegerField(default=6, help_text='Anti-bloqueo para envíos masivos/automáticos. Sugerido: Evolution 6–15 s, Meta/Twilio 1 s.', verbose_name='Segundos mínimos entre envíos automáticos')),
                ('evolution_instancia', models.SlugField(blank=True, max_length=100, verbose_name='Nombre de instancia')),
                ('evolution_api_url', models.CharField(blank=True, help_text='Vacío = valor global del .env', max_length=300)),
                ('evolution_api_key', models.CharField(blank=True, help_text='Vacío = valor global del .env', max_length=300)),
                ('meta_phone_number_id', models.CharField(blank=True, max_length=100, verbose_name='Phone Number ID')),
                ('meta_waba_id', models.CharField(blank=True, max_length=100, verbose_name='WhatsApp Business Account ID')),
                ('meta_access_token', models.CharField(blank=True, max_length=600, verbose_name='Access token permanente')),
                ('meta_app_secret', models.CharField(blank=True, max_length=200, verbose_name='App secret')),
                ('meta_verify_token', models.CharField(blank=True, max_length=200, verbose_name='Verify token del webhook')),
                ('meta_api_version', models.CharField(default='v21.0', max_length=10)),
                ('twilio_account_sid', models.CharField(blank=True, max_length=100, verbose_name='Account SID')),
                ('twilio_auth_token', models.CharField(blank=True, max_length=100, verbose_name='Auth token')),
                ('twilio_from', models.CharField(blank=True, help_text='Número habilitado en Twilio, ej: +14155238886', max_length=40, verbose_name='Número remitente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agentes', models.ManyToManyField(blank=True, help_text='Quiénes pueden usar esta línea. Vacío = todos los usuarios.', related_name='lineas_whatsapp', to=settings.AUTH_USER_MODEL)),
                ('embudo', models.ForeignKey(blank=True, help_text='Si escribe alguien que no está en el CRM, se crea una oportunidad en este embudo. Vacío = solo se crea el contacto y el chat.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineas_entrantes', to='crm.embudo', verbose_name='Embudo para contactos nuevos')),
            ],
            options={
                'verbose_name': 'Línea de WhatsApp',
                'verbose_name_plural': 'Líneas de WhatsApp',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=20)),
                ('nombre_perfil', models.CharField(blank=True, max_length=200)),
                ('estado', models.CharField(choices=[('pendiente', 'Sin atender'), ('abierta', 'En atención'), ('cerrada', 'Cerrada')], default='pendiente', max_length=10)),
                ('no_leidos', models.PositiveIntegerField(default=0)),
                ('ultimo_mensaje_at', models.DateTimeField(blank=True, null=True)),
                ('ultimo_entrante_at', models.DateTimeField(blank=True, null=True)),
                ('ultimo_mensaje_texto', models.CharField(blank=True, max_length=200)),
                ('archivada', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversaciones', to=settings.AUTH_USER_MODEL)),
                ('contacto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversaciones', to='crm.contacto')),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversaciones', to='whatsapp.lineawhatsapp')),
            ],
            options={
                'verbose_name': 'Conversación',
                'verbose_name_plural': 'Conversaciones',
                'ordering': ['-ultimo_mensaje_at'],
            },
        ),
        migrations.CreateModel(
            name='LogAPIWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=300)),
                ('metodo', models.CharField(max_length=10)),
                ('status', models.IntegerField(null=True)),
                ('request', models.TextField(blank=True)),
                ('response', models.TextField(blank=True)),
                ('exitoso', models.BooleanField(default=True)),
                ('duracion_ms', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('linea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='whatsapp.lineawhatsapp')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Plantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('cuerpo', models.TextField(help_text='Usá {{1}}, {{2}}… para variables.')),
                ('variables', models.JSONField(blank=True, default=list, help_text='Campo para cada variable, en orden.')),
                ('categoria', models.CharField(choices=[('MARKETING', 'Marketing'), ('UTILITY', 'Utilidad'), ('AUTHENTICATION', 'Autenticación')], default='MARKETING', max_length=20)),
                ('idioma', models.CharField(default='es_AR', max_length=10)),
                ('meta_nombre', models.CharField(blank=True, help_text='Nombre técnico en Meta (snake_case).', max_length=512)),
                ('meta_estado', models.CharField(choices=[('local', 'Solo local'), ('PENDING', 'En revisión en Meta'), ('APPROVED', 'Aprobada'), ('REJECTED', 'Rechazada')], default='local', max_length=10)),
                ('meta_rechazo', models.TextField(blank=True)),
                ('twilio_content_sid', models.CharField(blank=True, max_length=64, verbose_name='Twilio ContentSid (HX…)')),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('linea', models.ForeignKey(blank=True, help_text='Vacío = disponible en todas las líneas.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plantillas', to='whatsapp.lineawhatsapp')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(choices=[('in', 'Entrante'), ('out', 'Saliente')], max_length=3)),
                ('tipo', models.CharField(choices=[('text', 'Texto'), ('image', 'Imagen'), ('audio', 'Audio'), ('video', 'Video'), ('document', 'Documento'), ('template', 'Plantilla')], default='text', max_length=10)),
                ('contenido', models.TextField(blank=True)),
                ('media_url', models.CharField(blank=True, max_length=1000)),
                ('media_mime', models.CharField(blank=True, max_length=100)),
                ('media_filename', models.CharField(blank=True, max_length=255)),
                ('media_id', models.CharField(blank=True, max_length=200)),
                ('wa_id', models.CharField(blank=True, db_index=True, help_text='ID del mensaje en el proveedor', max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviado'), ('delivered', 'Entregado'), ('read', 'Leído'), ('failed', 'Fallido')], default='pending', max_length=10)),
                ('error', models.TextField(blank=True)),
                ('plantilla_valores', models.JSONField(blank=True, default=list)),
                ('automatico', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='whatsapp.conversacion')),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plantilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='whatsapp.plantilla')),
            ],
            options={
                'ordering': ['timestamp', 'pk'],
            },
        ),
        migrations.AddIndex(
            model_name='conversacion',
            index=models.Index(fields=['agente', 'archivada', '-ultimo_mensaje_at'], name='whatsapp_co_agente__f99921_idx'),
        ),
        migrations.AddIndex(
            model_name='conversacion',
            index=models.Index(fields=['archivada', '-ultimo_mensaje_at'], name='whatsapp_co_archiva_cb8df7_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversacion',
            constraint=models.UniqueConstraint(fields=('linea', 'telefono'), name='conversacion_unica_por_linea'),
        ),
        migrations.AddIndex(
            model_name='mensaje',
            index=models.Index(fields=['conversacion', 'timestamp'], name='whatsapp_me_convers_013a0d_idx'),
        ),
        migrations.AddConstraint(
            model_name='mensaje',
            constraint=models.UniqueConstraint(condition=models.Q(('wa_id', ''), _negated=True), fields=('wa_id',), name='mensaje_wa_id_unico'),
        ),
    ]
