# Generated by Django 5.1.4 on 2026-09-24 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineawhatsapp',
            name='proveedor',
            field=models.CharField(choices=[('evolution', 'Evolution API (QR, WhatsApp común o Business)'), ('meta', 'Meta Cloud API (oficial)'), ('twilio', 'Twilio (oficial vía BSP)'), ('demo', 'Simulado (demostración, no envía)')], default='evolution', max_length=15),
        ),
    ]
