# Generated by Django 5.1.4 on 2026-10-06 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatizaciones', '0006_emailenviado'),
        ('whatsapp', '0002_proveedor_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='accion',
            field=models.ForeignKey(blank=True, help_text='Automatización que lo envió (para medir respuesta).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes', to='automatizaciones.accionetapa'),
        ),
    ]
