# Generated by Django 5.1.4 on 2026-09-24 20:48

import apps.users.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('permisos', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rol personalizado',
                'verbose_name_plural': 'Roles personalizados',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('supervisor', 'Supervisor'), ('agente', 'Agente / Vendedor')], default='agente', max_length=20)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, verbose_name='email')),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='Teléfono / interno')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('disponible', models.BooleanField(default=True, help_text='Desactivar en vacaciones / licencia: deja de recibir prospectos nuevos.', verbose_name='Disponible para asignaciones')),
                ('debe_cambiar_password', models.BooleanField(default=False, verbose_name='Debe cambiar la contraseña al ingresar')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('rol_custom', models.ForeignKey(blank=True, help_text='Si se elige, define exactamente qué permisos tiene (reemplaza a los del rol base).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='users.rolpersonalizado', verbose_name='Rol personalizado')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['first_name', 'last_name', 'username'],
            },
            managers=[
                ('objects', apps.users.models.UsuarioManager()),
            ],
        ),
        migrations.CreateModel(
            name='NotificacionInterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('asignacion', 'Prospecto asignado'), ('tarea', 'Tarea'), ('llamada_perdida', 'Llamada perdida'), ('venta', 'Venta concretada'), ('estancado', 'Prospecto estancado'), ('mencion', 'Mención'), ('whatsapp', 'WhatsApp'), ('sistema', 'Sistema')], default='sistema', max_length=30)),
                ('titulo', models.CharField(max_length=200)),
                ('cuerpo', models.TextField(blank=True)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('leida', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['destinatario', 'leida', '-created_at'], name='users_notif_destina_f02697_idx')],
            },
        ),
    ]
