# Generated by Django 5.1.4 on 2026-10-06 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionConexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(db_index=True)),
                ('ultimo', models.DateTimeField(help_text='Último pulso recibido (si no hay "fin", la sesión terminó acá).')),
                ('fin', models.DateTimeField(blank=True, help_text='Salida explícita (botón Salir).', null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-inicio'],
                'indexes': [models.Index(fields=['usuario', 'inicio'], name='users_sesio_usuario_c0f889_idx')],
            },
        ),
    ]
