# Generated by Django 5.1.4 on 2026-09-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('prefijo', models.CharField(editable=False, max_length=12)),
                ('hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('fuente', models.CharField(blank=True, help_text='Texto que queda como "fuente" del lead.', max_length=150)),
                ('activa', models.BooleanField(default=True)),
                ('ultimo_uso_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'API key',
                'verbose_name_plural': 'API keys',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='LogIntegracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=200)),
                ('metodo', models.CharField(max_length=10)),
                ('status', models.PositiveSmallIntegerField()),
                ('ip', models.CharField(blank=True, max_length=60)),
                ('request', models.TextField(blank=True)),
                ('response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
