# Generated by Django 5.1.4 on 2026-09-24 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0003_initial'),
        ('integraciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='creada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apikey',
            name='embudo',
            field=models.ForeignKey(blank=True, help_text='Embudo por defecto para los leads que entran con esta clave.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.embudo'),
        ),
        migrations.AddField(
            model_name='logintegracion',
            name='api_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='integraciones.apikey'),
        ),
    ]
