# Generated by Django 5.1.4 on 2026-10-06 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integraciones', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigSMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=False)),
                ('account_sid', models.CharField(blank=True, max_length=64, verbose_name='Account SID')),
                ('auth_token', models.CharField(blank=True, max_length=128, verbose_name='Auth token')),
                ('numero', models.CharField(blank=True, help_text='El número de Twilio con SMS, en formato +1… / +54…, o un Messaging Service SID (MG…).', max_length=30, verbose_name='Número remitente')),
                ('webhook_token', models.CharField(blank=True, editable=False, max_length=40)),
            ],
            options={
                'verbose_name': 'Configuración SMS',
            },
        ),
    ]
