# Generated by Django 5.1.4 on 2026-09-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccionEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('whatsapp', 'Enviar WhatsApp al prospecto'), ('email', 'Enviar email al prospecto'), ('tarea', 'Crear tarea para el agente'), ('notif_agente', 'Notificar al agente'), ('notif_supervisores', 'Notificar a supervisión')], default='whatsapp', max_length=20)),
                ('activa', models.BooleanField(default=True)),
                ('demora_minutos', models.PositiveIntegerField(default=0, help_text='0 = inmediato. Ej: 1440 = al día siguiente.', verbose_name='Demora (minutos)')),
                ('solo_si_sigue_en_etapa', models.BooleanField(default=True, help_text='Evita mandar un seguimiento si el prospecto ya avanzó o se cerró.', verbose_name='Solo si sigue en esa etapa al momento de ejecutar')),
                ('solo_en_horario', models.BooleanField(default=True, help_text='Si cae fuera de horario se posterga hasta la próxima apertura (no se escribe de madrugada).', verbose_name='Ejecutar solo en el horario de atención del embudo')),
                ('texto', models.TextField(blank=True, help_text='Mensaje libre (líneas Evolution / email). Variables: {nombre} {primer_nombre} {agente} {embudo} {etapa}')),
                ('email_asunto', models.CharField(blank=True, max_length=200)),
                ('tarea_titulo', models.CharField(blank=True, max_length=200)),
                ('tarea_vence_horas', models.PositiveSmallIntegerField(default=24)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Automatización',
                'verbose_name_plural': 'Automatizaciones',
                'ordering': ['embudo', 'etapa__orden', 'orden', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='EjecucionAccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('ejecutada', 'Ejecutada'), ('omitida', 'Omitida'), ('error', 'Error')], db_index=True, default='programada', max_length=12)),
                ('programada_para', models.DateTimeField()),
                ('ejecutada_at', models.DateTimeField(blank=True, null=True)),
                ('detalle', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
