# Generated by Django 5.1.4 on 2026-09-24 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('automatizaciones', '0001_initial'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accionetapa',
            name='embudo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones', to='crm.embudo'),
        ),
        migrations.AddField(
            model_name='accionetapa',
            name='etapa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones', to='crm.etapa', verbose_name='Cuando entra a la etapa'),
        ),
    ]
