# Generated by Django 5.1.4 on 2026-09-24 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('automatizaciones', '0002_initial'),
        ('crm', '0002_initial'),
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accionetapa',
            name='linea',
            field=models.ForeignKey(blank=True, help_text='Vacío = la del chat existente o la del embudo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='whatsapp.lineawhatsapp'),
        ),
        migrations.AddField(
            model_name='accionetapa',
            name='plantilla',
            field=models.ForeignKey(blank=True, help_text='Obligatoria para líneas oficiales (Meta/Twilio).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='whatsapp.plantilla'),
        ),
        migrations.AddField(
            model_name='ejecucionaccion',
            name='accion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejecuciones', to='automatizaciones.accionetapa'),
        ),
        migrations.AddField(
            model_name='ejecucionaccion',
            name='historial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.historialetapa'),
        ),
        migrations.AddField(
            model_name='ejecucionaccion',
            name='oportunidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejecuciones', to='crm.oportunidad'),
        ),
        migrations.AddIndex(
            model_name='ejecucionaccion',
            index=models.Index(fields=['estado', 'programada_para'], name='automatizac_estado_383705_idx'),
        ),
        migrations.AddConstraint(
            model_name='ejecucionaccion',
            constraint=models.UniqueConstraint(fields=('accion', 'historial'), name='ejecucion_unica_por_entrada'),
        ),
    ]
