# Generated by Django 5.1.4 on 2026-10-03 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatizaciones', '0003_initial'),
        ('crm', '0010_oportunidad_embudo_previo_oportunidad_etapa_previa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accionetapa',
            name='asignar_destino',
            field=models.CharField(choices=[('mismo', 'Al mismo agente'), ('embudo', 'Según la regla del embudo de destino'), ('usuario', 'A un usuario fijo')], default='mismo', max_length=10, verbose_name='Asignar'),
        ),
        migrations.AddField(
            model_name='accionetapa',
            name='embudo_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.embudo', verbose_name='Embudo de destino'),
        ),
        migrations.AddField(
            model_name='accionetapa',
            name='etapa_destino',
            field=models.ForeignKey(blank=True, help_text='Vacío = la primera etapa.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.etapa', verbose_name='Etapa de destino'),
        ),
        migrations.AddField(
            model_name='accionetapa',
            name='modo_embudo',
            field=models.CharField(choices=[('crear', 'Crear una oportunidad nueva en otro embudo (la actual queda como está)'), ('mover', 'Mover esta misma tarjeta a otro embudo'), ('volver', 'Volver al embudo del que vino')], default='crear', max_length=10, verbose_name='Cómo'),
        ),
        migrations.AddField(
            model_name='accionetapa',
            name='usuario_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='accionetapa',
            name='volver_a',
            field=models.CharField(choices=[('misma', 'A la etapa donde estaba'), ('siguiente', 'A la etapa siguiente')], default='misma', max_length=10, verbose_name='Al volver, ir'),
        ),
        migrations.AlterField(
            model_name='accionetapa',
            name='tipo',
            field=models.CharField(choices=[('whatsapp', 'Enviar WhatsApp al prospecto'), ('email', 'Enviar email al prospecto'), ('tarea', 'Crear tarea para el agente'), ('notif_agente', 'Notificar al agente'), ('notif_supervisores', 'Notificar a supervisión'), ('embudo', 'Pasar a otro embudo')], default='whatsapp', max_length=20),
        ),
    ]
