# Generated by Django 5.1.4 on 2026-10-06 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatizaciones', '0004_accionetapa_asignar_destino_and_more'),
        ('crm', '0012_sla'),
    ]

    operations = [
        migrations.AddField(
            model_name='accionetapa',
            name='disparador',
            field=models.CharField(choices=[('entrada', 'Al entrar a la etapa'), ('sin_respuesta', 'Si el cliente no responde (en el tiempo de demora desde que entró a la etapa)'), ('respuesta', 'Cuando el cliente responde (WhatsApp o llamada atendida) estando en la etapa'), ('sin_actividad', 'Si no hay ninguna actividad durante el tiempo de demora')], default='entrada', max_length=15, verbose_name='Cuándo'),
        ),
        migrations.AddField(
            model_name='accionetapa',
            name='mover_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.etapa', verbose_name='Mover a la etapa'),
        ),
        migrations.AddField(
            model_name='accionetapa',
            name='tipificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.tipificacion', verbose_name='Tipificación (si cierra)'),
        ),
        migrations.AlterField(
            model_name='accionetapa',
            name='tipo',
            field=models.CharField(choices=[('whatsapp', 'Enviar WhatsApp al prospecto'), ('email', 'Enviar email al prospecto'), ('tarea', 'Crear tarea para el agente'), ('notif_agente', 'Notificar al agente'), ('notif_supervisores', 'Notificar a supervisión'), ('embudo', 'Pasar a otro embudo'), ('etapa', 'Mover a otra etapa / cerrar')], default='whatsapp', max_length=20),
        ),
    ]
