# Generated by Django 5.1.4 on 2026-10-06 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatizaciones', '0005_disparadores'),
        ('crm', '0012_sla'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailEnviado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('para', models.EmailField(max_length=254)),
                ('asunto', models.CharField(max_length=200)),
                ('token', models.CharField(max_length=40, unique=True)),
                ('enviado_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('abierto_at', models.DateTimeField(blank=True, null=True)),
                ('aperturas', models.PositiveIntegerField(default=0)),
                ('clic_at', models.DateTimeField(blank=True, null=True)),
                ('clics', models.PositiveIntegerField(default=0)),
                ('accion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='automatizaciones.accionetapa')),
                ('contacto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.contacto')),
                ('oportunidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.oportunidad')),
            ],
            options={
                'ordering': ['-enviado_at'],
            },
        ),
    ]
