# Generated by Django 5.1.4 on 2026-10-06 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatizaciones', '0006_emailenviado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emailenviado',
            name='enviado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accionetapa',
            name='tipo',
            field=models.CharField(choices=[('whatsapp', 'Enviar WhatsApp al prospecto'), ('email', 'Enviar email al prospecto'), ('sms', 'Enviar SMS al prospecto'), ('tarea', 'Crear tarea para el agente'), ('notif_agente', 'Notificar al agente'), ('notif_supervisores', 'Notificar a supervisión'), ('embudo', 'Pasar a otro embudo'), ('etapa', 'Mover a otra etapa / cerrar')], default='whatsapp', max_length=20),
        ),
    ]
