# Generated by Django 5.1.4 on 2026-10-07 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatizaciones', '0007_emailenviado_enviado_por_alter_accionetapa_tipo'),
        ('crm', '0015_contacto_no_email_contacto_no_email_at'),
        ('whatsapp', '0003_mensaje_accion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=False, verbose_name='Usar esta configuración')),
                ('host', models.CharField(blank=True, max_length=200, verbose_name='Servidor SMTP')),
                ('puerto', models.PositiveIntegerField(default=587)),
                ('usuario', models.CharField(blank=True, max_length=200)),
                ('password', models.CharField(blank=True, max_length=300, verbose_name='Contraseña')),
                ('seguridad', models.CharField(choices=[('tls', 'STARTTLS (587)'), ('ssl', 'SSL (465)'), ('', 'Ninguna')], default='tls', max_length=5)),
                ('remitente', models.CharField(blank=True, help_text='Ej: "Roisa Ventas <ventas@roisa.com.ar>". Tiene que estar autorizado en el servidor.', max_length=200, verbose_name='Remitente')),
                ('por_minuto', models.PositiveSmallIntegerField(default=30, help_text='Gmail: no más de ~500 por día. Brevo / SES / Mailgun: más.', verbose_name='Emails por minuto en difusiones')),
            ],
            options={
                'verbose_name': 'Configuración de email',
            },
        ),
        migrations.CreateModel(
            name='PlantillaEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('asunto', models.CharField(max_length=200)),
                ('cuerpo', models.TextField(help_text='Texto del email. Los links se miden solos. Variables: {nombre} {primer_nombre} {agente} {embudo} {etapa} y los campos personalizados.')),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='accionetapa',
            name='accion_previa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='siguientes', to='automatizaciones.accionetapa', verbose_name='Después de la automatización'),
        ),
        migrations.AddField(
            model_name='emailenviado',
            name='baja_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accionetapa',
            name='disparador',
            field=models.CharField(choices=[('entrada', 'Al entrar a la etapa'), ('sin_respuesta', 'Si el cliente no responde (en el tiempo de demora desde que entró a la etapa)'), ('respuesta', 'Cuando el cliente responde (WhatsApp o llamada atendida) estando en la etapa'), ('sin_actividad', 'Si no hay ninguna actividad durante el tiempo de demora'), ('despues_de', 'Después de que se ejecutó otra automatización (secuencia)')], default='entrada', max_length=15, verbose_name='Cuándo'),
        ),
        migrations.CreateModel(
            name='Difusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('canal', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp')], default='email', max_length=10)),
                ('texto_wa', models.TextField(blank=True, verbose_name='Texto (solo líneas no oficiales, sin plantilla)')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('programada', 'Programada'), ('enviando', 'Enviando'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], db_index=True, default='borrador', max_length=12)),
                ('programada_para', models.DateTimeField(blank=True, null=True)),
                ('descripcion_filtro', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('iniciada_at', models.DateTimeField(blank=True, null=True)),
                ('finalizada_at', models.DateTimeField(blank=True, null=True)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('linea', models.ForeignKey(blank=True, help_text='Vacío = la del chat existente o la del embudo de cada lead.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='whatsapp.lineawhatsapp')),
                ('plantilla_wa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='whatsapp.plantilla', verbose_name='Plantilla de WhatsApp')),
                ('plantilla_email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='automatizaciones.plantillaemail')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='emailenviado',
            name='difusion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='automatizaciones.difusion'),
        ),
        migrations.AddField(
            model_name='accionetapa',
            name='plantilla_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='automatizaciones.plantillaemail', verbose_name='Plantilla de email'),
        ),
        migrations.AddField(
            model_name='emailenviado',
            name='plantilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='automatizaciones.plantillaemail'),
        ),
        migrations.CreateModel(
            name='DifusionDestinatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('omitido', 'Omitido'), ('error', 'Error')], db_index=True, default='pendiente', max_length=10)),
                ('detalle', models.CharField(blank=True, max_length=300)),
                ('enviado_at', models.DateTimeField(blank=True, null=True)),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='crm.contacto')),
                ('difusion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatarios', to='automatizaciones.difusion')),
                ('email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='automatizaciones.emailenviado')),
                ('mensaje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='whatsapp.mensaje')),
                ('oportunidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.oportunidad')),
            ],
            options={
                'indexes': [models.Index(fields=['difusion', 'estado'], name='automatizac_difusio_abe445_idx')],
                'constraints': [models.UniqueConstraint(fields=('difusion', 'contacto'), name='difusion_contacto_unico')],
            },
        ),
    ]
