# Generated by Django 5.1.4 on 2026-10-09 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatizaciones', '0008_configemail_plantillaemail_accionetapa_accion_previa_and_more'),
        ('crm', '0016_embudo_etiqueta_venta_embudo_exigir_resultado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accionetapa',
            name='etiqueta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.etiqueta'),
        ),
        migrations.AddField(
            model_name='accionetapa',
            name='otras_etapas',
            field=models.ManyToManyField(blank=True, related_name='+', to='crm.etapa', verbose_name='También en estas etapas'),
        ),
        migrations.AddField(
            model_name='accionetapa',
            name='reparto',
            field=models.CharField(choices=[('menor_carga', 'Al que tenga menos prospectos abiertos (parejo)'), ('embudo', 'Según la regla del embudo (rotativa / menor carga)')], default='menor_carga', max_length=12, verbose_name='Repartir'),
        ),
        migrations.AddField(
            model_name='accionetapa',
            name='todas_las_etapas',
            field=models.BooleanField(default=False, verbose_name='En todas las etapas abiertas del embudo'),
        ),
        migrations.AddField(
            model_name='accionetapa',
            name='volver_a_etapa',
            field=models.ForeignKey(blank=True, help_text='Opcional (ej. "Nuevo"), para que se trabaje de cero.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.etapa', verbose_name='Y volverla a la etapa'),
        ),
        migrations.AlterField(
            model_name='accionetapa',
            name='disparador',
            field=models.CharField(choices=[('entrada', 'Al entrar a la etapa'), ('sin_respuesta', 'Si el cliente no responde (en el tiempo de demora desde que entró a la etapa)'), ('respuesta', 'Cuando el cliente responde (WhatsApp o llamada atendida) estando en la etapa'), ('sin_actividad', 'Si no hay ninguna actividad durante el tiempo de demora'), ('despues_de', 'Después de que se ejecutó otra automatización (secuencia)'), ('reingreso', 'Cuando el lead reingresa (vuelve a escribir, llenar un formulario o se importa de nuevo)')], default='entrada', max_length=15, verbose_name='Cuándo'),
        ),
        migrations.AlterField(
            model_name='accionetapa',
            name='tipo',
            field=models.CharField(choices=[('whatsapp', 'Enviar WhatsApp al prospecto'), ('email', 'Enviar email al prospecto'), ('sms', 'Enviar SMS al prospecto'), ('tarea', 'Crear tarea para el agente'), ('notif_agente', 'Notificar al agente'), ('notif_supervisores', 'Notificar a supervisión'), ('embudo', 'Pasar a otro embudo'), ('etapa', 'Mover a otra etapa / cerrar'), ('reasignar', 'Reasignar a otro vendedor (reproceso)'), ('prioridad', 'Marcar como prioridad'), ('etiqueta', 'Poner una etiqueta al contacto')], default='whatsapp', max_length=20),
        ),
    ]
