# Generated by Django 5.1.4 on 2026-10-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatizaciones', '0009_accionetapa_etiqueta_accionetapa_otras_etapas_and_more'),
        ('crm', '0017_embudo_clientes_de_otros'),
        ('pautas', '0002_whatsapp_anuncios_palabras'),
    ]

    operations = [
        migrations.AddField(
            model_name='accionetapa',
            name='excluir_etiquetas',
            field=models.ManyToManyField(blank=True, related_name='+', to='crm.etiqueta', verbose_name='Nunca si tiene alguna de estas etiquetas'),
        ),
        migrations.AddField(
            model_name='accionetapa',
            name='solo_etiquetas',
            field=models.ManyToManyField(blank=True, related_name='+', to='crm.etiqueta', verbose_name='Solo si el contacto tiene alguna de estas etiquetas'),
        ),
        migrations.AddField(
            model_name='accionetapa',
            name='solo_pautas',
            field=models.ManyToManyField(blank=True, related_name='+', to='pautas.pauta', verbose_name='Solo leads de estas pautas / campañas'),
        ),
    ]
