# Generated by Django 5.1.4 on 2026-09-24 20:48

import apps.telefonia.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgenteDiscador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_pausa', models.BooleanField(default=False)),
                ('libre_desde', models.DateTimeField(default=django.utils.timezone.now)),
                ('conectado_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CampaniaContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_curso', 'En curso'), ('reintentar', 'A reintentar'), ('contactado', 'Contactado'), ('no_contesta', 'No contesta (agotó intentos)'), ('descartado', 'Descartado')], default='pendiente', max_length=12)),
                ('intentos', models.PositiveSmallIntegerField(default=0)),
                ('ultimo_intento_at', models.DateTimeField(blank=True, null=True)),
                ('proximo_intento_at', models.DateTimeField(blank=True, null=True)),
                ('prioridad', models.SmallIntegerField(default=0)),
                ('detalle', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-prioridad', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='CampaniaDiscado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('activa', 'Activa'), ('pausada', 'Pausada'), ('finalizada', 'Finalizada')], default='borrador', max_length=10)),
                ('max_intentos', models.PositiveSmallIntegerField(default=3, verbose_name='Máximo de intentos por contacto')),
                ('minutos_entre_intentos', models.PositiveIntegerField(default=120, verbose_name='Minutos entre reintentos')),
                ('hora_desde', models.TimeField(default='09:00')),
                ('hora_hasta', models.TimeField(default='20:00')),
                ('dias', models.JSONField(blank=True, default=list, help_text='0=lunes … 6=domingo. Vacío = lunes a viernes.')),
                ('segundos_entre_llamadas', models.PositiveSmallIntegerField(default=15, help_text='Tiempo para tipificar antes de que el discador le pase la próxima llamada.', verbose_name='Pausa del agente entre llamadas (s)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Campaña de discado',
                'verbose_name_plural': 'Campañas de discado',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConfigAnura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=False, verbose_name='Integración activa')),
                ('modo_demo', models.BooleanField(default=True, help_text='Simula las llamadas sin conectarse a Anura (para capacitación y presentaciones).', verbose_name='Modo demostración')),
                ('api_url', models.CharField(blank=True, help_text='Ej: https://api.anura.com.ar (confirmar con soporte de Anura).', max_length=300, verbose_name='URL base de la API')),
                ('auth_tipo', models.CharField(choices=[('bearer', 'Bearer token'), ('basic', 'Usuario y contraseña (Basic)'), ('header', 'Header personalizado')], default='bearer', max_length=10)),
                ('api_token', models.CharField(blank=True, max_length=500)),
                ('api_usuario', models.CharField(blank=True, max_length=150)),
                ('api_password', models.CharField(blank=True, max_length=300)),
                ('auth_header_nombre', models.CharField(blank=True, default='X-Api-Key', max_length=60)),
                ('tenant_id', models.CharField(blank=True, max_length=100)),
                ('account_id', models.CharField(blank=True, max_length=100, verbose_name='Account ID')),
                ('webhook_token', models.CharField(default=apps.telefonia.models._token, editable=False, max_length=64)),
                ('crear_tarjeta_salientes', models.BooleanField(default=True, help_text='Si un agente llama desde el softphone a un número que no está en el CRM, se crea la oportunidad.', verbose_name='Crear tarjeta en llamadas salientes a números nuevos')),
                ('tarea_llamada_perdida', models.BooleanField(default=True, verbose_name='Crear tarea "Devolver llamada" si no se atiende')),
                ('descargar_grabaciones', models.BooleanField(default=True)),
                ('polling_activo', models.BooleanField(default=True, help_text='Cada 5 min recupera llamadas cuyo webhook no llegó.', verbose_name='Polling de respaldo de CDRs')),
                ('ultimo_polling_ok', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración Anura',
            },
        ),
        migrations.CreateModel(
            name='InternoAnura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interno', models.CharField(help_text='Identificador del terminal del agente en Anura.', max_length=50, unique=True, verbose_name='Interno / terminal')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Interno de Anura',
                'verbose_name_plural': 'Internos de Anura',
                'ordering': ['interno'],
            },
        ),
        migrations.CreateModel(
            name='Llamada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.CharField(blank=True, help_text='callId de Anura: garantiza que una llamada no se procese dos veces.', max_length=100, null=True, unique=True)),
                ('anura_uuid', models.CharField(blank=True, db_index=True, max_length=100)),
                ('direccion', models.CharField(choices=[('IN', 'Entrante'), ('OUT', 'Saliente')], max_length=3)),
                ('estado', models.CharField(choices=[('discando', 'Discando'), ('sonando', 'Sonando'), ('en_curso', 'En curso'), ('atendida', 'Atendida'), ('no_atendida', 'No atendida'), ('ocupado', 'Ocupado'), ('fallida', 'Fallida')], db_index=True, default='discando', max_length=12)),
                ('numero', models.CharField(blank=True, db_index=True, help_text='Número del cliente, normalizado', max_length=20)),
                ('numero_crudo', models.CharField(blank=True, max_length=60)),
                ('did', models.CharField(blank=True, help_text='Número/servicio marcado (called)', max_length=60)),
                ('queue_id', models.CharField(blank=True, max_length=60)),
                ('interno', models.CharField(blank=True, max_length=50)),
                ('inicio_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('atendida_at', models.DateTimeField(blank=True, null=True)),
                ('fin_at', models.DateTimeField(blank=True, null=True)),
                ('duracion_seg', models.PositiveIntegerField(default=0, help_text='Segundos facturados (billSeconds)')),
                ('grabada', models.BooleanField(default=False)),
                ('grabacion', models.FileField(blank=True, upload_to='grabaciones/%Y/%m/')),
                ('grabacion_estado', models.CharField(blank=True, max_length=10)),
                ('origen_registro', models.CharField(blank=True, help_text='webhook / polling / click2call / discador / demo', max_length=15)),
                ('procesada', models.BooleanField(default=False, help_text='Se aplicó la lógica de fin de llamada.')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-inicio_at'],
            },
        ),
        migrations.CreateModel(
            name='RutaAnura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('did', 'Número marcado (DID)'), ('cola', 'Cola (queueId)')], default='did', max_length=5)),
                ('valor', models.CharField(help_text='El DID tal como lo manda Anura (campo "called") o el queueId.', max_length=60)),
                ('descripcion', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'verbose_name': 'Ruta de Anura',
                'verbose_name_plural': 'Rutas de Anura',
            },
        ),
    ]
