# Generated by Django 5.1.4 on 2026-09-24 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0003_initial'),
        ('telefonia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agentediscador',
            name='agente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sesion_discador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaniacontacto',
            name='agente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaniacontacto',
            name='contacto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='crm.contacto'),
        ),
        migrations.AddField(
            model_name='campaniacontacto',
            name='oportunidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campanias_discado', to='crm.oportunidad'),
        ),
        migrations.AddField(
            model_name='campaniadiscado',
            name='agentes',
            field=models.ManyToManyField(blank=True, related_name='campanias_discado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaniadiscado',
            name='creada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaniadiscado',
            name='embudo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campanias', to='crm.embudo'),
        ),
        migrations.AddField(
            model_name='campaniacontacto',
            name='campania',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='telefonia.campaniadiscado'),
        ),
        migrations.AddField(
            model_name='agentediscador',
            name='campania',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='telefonia.campaniadiscado'),
        ),
        migrations.AddField(
            model_name='configanura',
            name='embudo_entrantes',
            field=models.ForeignKey(blank=True, help_text='Si el DID/cola no tiene un embudo mapeado, las llamadas nuevas entran acá.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.embudo', verbose_name='Embudo para llamadas de números desconocidos'),
        ),
        migrations.AddField(
            model_name='internoanura',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interno_anura', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='llamada',
            name='agente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llamadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='llamada',
            name='campania_contacto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llamadas', to='telefonia.campaniacontacto'),
        ),
        migrations.AddField(
            model_name='llamada',
            name='contacto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llamadas', to='crm.contacto'),
        ),
        migrations.AddField(
            model_name='llamada',
            name='oportunidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llamadas', to='crm.oportunidad'),
        ),
        migrations.AddField(
            model_name='rutaanura',
            name='agente',
            field=models.ForeignKey(blank=True, help_text='Opcional: asignar siempre a este agente.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rutaanura',
            name='embudo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas_anura', to='crm.embudo'),
        ),
        migrations.AddIndex(
            model_name='campaniacontacto',
            index=models.Index(fields=['campania', 'estado', 'proximo_intento_at'], name='telefonia_c_campani_1d22ee_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campaniacontacto',
            unique_together={('campania', 'telefono')},
        ),
        migrations.AddIndex(
            model_name='llamada',
            index=models.Index(fields=['agente', 'estado'], name='telefonia_l_agente__2a085a_idx'),
        ),
        migrations.AddIndex(
            model_name='llamada',
            index=models.Index(fields=['contacto', '-inicio_at'], name='telefonia_l_contact_66c1c2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rutaanura',
            unique_together={('tipo', 'valor')},
        ),
    ]
