# Generated by Django 5.1.4 on 2026-09-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefonia', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internoanura',
            name='alias',
            field=models.CharField(blank=True, help_text='Otros identificadores con los que Anura puede nombrar este teléfono en los avisos (usuario SIP, ID de terminal…). Varios separados por coma.', max_length=200, verbose_name='Alias en Anura'),
        ),
        migrations.AlterField(
            model_name='internoanura',
            name='interno',
            field=models.CharField(help_text='Identificador que se usa para originar y cortar llamadas en Anura.', max_length=50, unique=True, verbose_name='Interno / terminal'),
        ),
    ]
