# Generated by Django 5.1.4 on 2026-09-25 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefonia', '0003_interno_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='configanura',
            name='click2dial_token',
            field=models.CharField(blank=True, help_text='Se genera en el panel de Anura: Integraciones → Click 2 Dial.', max_length=500, verbose_name='Token de Click2Dial'),
        ),
        migrations.AddField(
            model_name='configanura',
            name='click2dial_url',
            field=models.CharField(default='https://api.anura.com.ar/adapter/default/click2call', help_text='Argentina: api.anura.com.ar · Perú: api.anura.pe', max_length=300, verbose_name='URL de Click2Dial'),
        ),
        migrations.AlterField(
            model_name='configanura',
            name='api_url',
            field=models.CharField(blank=True, help_text='Solo si Anura habilita la API de tenant (CDRs, números bloqueados).', max_length=300, verbose_name='URL de la API de tenant (opcional)'),
        ),
        migrations.AlterField(
            model_name='configanura',
            name='polling_activo',
            field=models.BooleanField(default=False, help_text='Requiere la API de tenant. Cada 5 min recupera llamadas cuyo evento no llegó.', verbose_name='Polling de respaldo de CDRs'),
        ),
    ]
