# Generated by Django 5.1.4 on 2026-09-25 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefonia', '0004_click2dial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configanura',
            name='webphone_url',
            field=models.CharField(blank=True, help_text='La que usan los agentes para atender y cortar en el navegador. Muestra el botón "Ir a Anura" en el aviso de llamada. Vacío = sin botón.', max_length=300, verbose_name='Dirección del Anura web de los agentes'),
        ),
    ]
