# Generated by Django 5.1.4 on 2026-09-29 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefonia', '0005_webphone_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='configanura',
            name='solo_eventos_propios',
            field=models.BooleanField(default=False, help_text='Ignora las llamadas de la central que no pasan por un interno asociado a un usuario, una ruta (DID/cola) cargada acá o un "Llamar" del CRM. Útil si la cuenta de Anura se comparte con otras áreas.', verbose_name='Procesar solo llamadas de internos o rutas del CRM'),
        ),
    ]
