# Generated by Django 5.1.4 on 2026-10-09 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_embudo_etiqueta_venta_embudo_exigir_resultado_and_more'),
        ('telefonia', '0006_solo_eventos_propios'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='llamada',
            name='calificada_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='llamada',
            name='calificada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='llamada',
            name='resultado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='llamadas', to='crm.resultadogestion'),
        ),
        migrations.AddField(
            model_name='llamada',
            name='resultado_nota',
            field=models.TextField(blank=True),
        ),
    ]
