# Generated by Django 5.1.4 on 2026-09-24 20:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('nota', 'Nota'), ('llamada', 'Llamada'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('etapa', 'Cambio de etapa'), ('asignacion', 'Asignación'), ('intento', 'Intento de contacto'), ('tarea', 'Tarea'), ('pausa', 'Pausa / reactivación'), ('cierre', 'Cierre'), ('reingreso', 'Reingreso del dato'), ('sistema', 'Sistema')], max_length=15)),
                ('texto', models.TextField(blank=True)),
                ('datos', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre y apellido')),
                ('telefono', models.CharField(blank=True, db_index=True, help_text='Se normaliza a formato internacional (+549…). Es la clave anti-duplicados.', max_length=20, verbose_name='Teléfono')),
                ('telefono_alternativo', models.CharField(blank=True, db_index=True, max_length=20)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('dni', models.CharField(blank=True, db_index=True, max_length=12, verbose_name='DNI')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('localidad', models.CharField(blank=True, max_length=100)),
                ('provincia', models.CharField(blank=True, max_length=100)),
                ('fecha_atencion', models.DateField(blank=True, null=True, verbose_name='Fecha de atención en el centro médico')),
                ('especialidad_atencion', models.CharField(blank=True, help_text='Opcional: permite segmentar el discurso comercial.', max_length=120, verbose_name='Motivo / especialidad de la consulta')),
                ('datos_extra', models.JSONField(blank=True, default=dict, help_text='Columnas adicionales de importaciones / integraciones.')),
                ('no_contactar', models.BooleanField(db_index=True, default=False, help_text='Pidió no recibir comunicaciones: se bloquean mensajes y discador.', verbose_name='No contactar')),
                ('no_contactar_desde', models.DateTimeField(blank=True, null=True)),
                ('telefono_invalido', models.BooleanField(default=False, verbose_name='Teléfono inválido')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Embudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=60, unique=True)),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('color', models.CharField(choices=[('#3B7EF6', 'Azul'), ('#7C5CFC', 'Violeta'), ('#06B6D4', 'Celeste'), ('#22C97A', 'Verde'), ('#F59E0B', 'Ámbar'), ('#F97316', 'Naranja'), ('#EF4444', 'Rojo'), ('#EC4899', 'Rosa'), ('#64748B', 'Gris')], default='#3B7EF6', max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('modo_asignacion', models.CharField(choices=[('round_robin', 'Rotativa (round robin) entre agentes habilitados'), ('menor_carga', 'Al agente con menos prospectos abiertos'), ('manual', 'Manual (la asigna un supervisor)')], default='round_robin', max_length=20)),
                ('respetar_horario', models.BooleanField(default=False, verbose_name='Asignar solo en horario de atención')),
                ('horario_desde', models.TimeField(default='09:00')),
                ('horario_hasta', models.TimeField(default='18:00')),
                ('dias_habiles', models.JSONField(blank=True, default=list, help_text='0=lunes … 6=domingo')),
                ('fuera_de_horario', models.CharField(choices=[('encolar', 'Dejar en cola y asignar al abrir el horario'), ('asignar', 'Asignar igual')], default='encolar', max_length=10)),
                ('crear_tarea_al_asignar', models.BooleanField(default=True, verbose_name='Crear tarea "Contactar prospecto" al asignar')),
                ('max_intentos_sin_respuesta', models.PositiveSmallIntegerField(default=5, verbose_name='Intentos antes de sugerir "Sin respuesta"')),
                ('dias_inactividad_recordatorio', models.PositiveSmallIntegerField(default=3, help_text='0 = desactivado', verbose_name='Días sin actividad para recordar al agente')),
                ('dias_estancado_alerta', models.PositiveSmallIntegerField(default=7, help_text='0 = desactivado', verbose_name='Días en la misma etapa para avisar a supervisión')),
                ('notificar_venta_supervisores', models.BooleanField(default=True, verbose_name='Avisar a supervisión cada venta')),
                ('reingreso_perdidos', models.CharField(choices=[('nueva', 'Abrir una oportunidad nueva'), ('ignorar', 'No abrir: solo registrar el reingreso en la ficha')], default='nueva', max_length=10, verbose_name='Si reingresa un prospecto que se perdió antes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Embudo',
                'verbose_name_plural': 'Embudos',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.CharField(blank=True, max_length=300)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('color', models.CharField(choices=[('#3B7EF6', 'Azul'), ('#7C5CFC', 'Violeta'), ('#06B6D4', 'Celeste'), ('#22C97A', 'Verde'), ('#F59E0B', 'Ámbar'), ('#F97316', 'Naranja'), ('#EF4444', 'Rojo'), ('#EC4899', 'Rosa'), ('#64748B', 'Gris')], default='#3B7EF6', max_length=10)),
                ('tipo', models.CharField(choices=[('normal', 'En proceso'), ('ganado', 'Cierre ganado (Venta)'), ('perdido', 'Cierre perdido (No venta)')], default='normal', max_length=10)),
                ('marca_contacto_efectivo', models.BooleanField(default=False, help_text='Se usa para medir tasa de contactabilidad.', verbose_name='Llegar acá cuenta como "contacto efectivo"')),
            ],
            options={
                'verbose_name': 'Etapa',
                'verbose_name_plural': 'Etapas',
                'ordering': ['embudo', 'orden', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(choices=[('#3B7EF6', 'Azul'), ('#7C5CFC', 'Violeta'), ('#06B6D4', 'Celeste'), ('#22C97A', 'Verde'), ('#F59E0B', 'Ámbar'), ('#F97316', 'Naranja'), ('#EF4444', 'Rojo'), ('#EC4899', 'Rosa'), ('#64748B', 'Gris')], default='#64748B', max_length=10)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='HistorialEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, max_length=10)),
                ('estado_nuevo', models.CharField(blank=True, max_length=10)),
                ('nota', models.CharField(blank=True, max_length=300)),
                ('segundos_en_etapa_anterior', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportacionLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='importaciones/%Y/%m/')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('fuente', models.CharField(blank=True, help_text='Ej: "Base centro médico – septiembre".', max_length=150)),
                ('mapeo', models.JSONField(blank=True, default=dict, help_text='{columna_archivo: campo_crm}')),
                ('asignar_automaticamente', models.BooleanField(default=True)),
                ('disparar_automatizaciones', models.BooleanField(default=True, help_text='Mensajes de bienvenida y demás acciones de la etapa.')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completado', 'Completado'), ('error', 'Error')], default='pendiente', max_length=12)),
                ('total', models.PositiveIntegerField(default=0)),
                ('procesados', models.PositiveIntegerField(default=0)),
                ('creados', models.PositiveIntegerField(default=0, help_text='Oportunidades nuevas')),
                ('contactos_nuevos', models.PositiveIntegerField(default=0)),
                ('ya_existentes', models.PositiveIntegerField(default=0, help_text='Ya tenían una oportunidad activa: no se duplicó')),
                ('errores', models.PositiveIntegerField(default=0)),
                ('errores_detalle', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finalizado_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Importación',
                'verbose_name_plural': 'Importaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Oportunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('abierta', 'En curso'), ('pausada', 'Pausada'), ('ganada', 'Venta'), ('perdida', 'No venta')], default='abierta', max_length=10)),
                ('pendiente_asignacion', models.BooleanField(default=False, help_text='Ingresó fuera de horario y espera asignación.')),
                ('origen', models.CharField(choices=[('importacion', 'Importación de base'), ('api', 'Integración / API'), ('web', 'Formulario web'), ('whatsapp', 'WhatsApp entrante'), ('llamada_entrante', 'Llamada entrante'), ('llamada_saliente', 'Llamada saliente'), ('manual', 'Carga manual')], default='manual', max_length=20)),
                ('fuente', models.CharField(blank=True, help_text='Detalle del origen: nombre de la base, landing, DID…', max_length=150)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor / cuota ($)')),
                ('nota_cierre', models.TextField(blank=True)),
                ('cerrada_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('intentos_contacto', models.PositiveSmallIntegerField(default=0)),
                ('ultimo_intento_at', models.DateTimeField(blank=True, null=True)),
                ('contacto_efectivo_at', models.DateTimeField(blank=True, null=True)),
                ('ultima_actividad_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('etapa_desde', models.DateTimeField(default=django.utils.timezone.now)),
                ('proximo_contacto_at', models.DateTimeField(blank=True, help_text='Pausada hasta / fecha de recontacto.', null=True)),
                ('motivo_pausa', models.CharField(blank=True, max_length=200)),
                ('asignada_at', models.DateTimeField(blank=True, null=True)),
                ('recordatorio_enviado_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('alerta_estancado_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('datos_extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Oportunidad',
                'verbose_name_plural': 'Oportunidades',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('llamada', 'Llamar'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('seguimiento', 'Seguimiento'), ('reactivacion', 'Reactivación'), ('otro', 'Otro')], default='llamada', max_length=15)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('vence_at', models.DateTimeField(verbose_name='Vence')),
                ('prioridad', models.CharField(choices=[('alta', 'Alta'), ('normal', 'Normal'), ('baja', 'Baja')], default='normal', max_length=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=12)),
                ('resultado', models.TextField(blank=True)),
                ('completada_at', models.DateTimeField(blank=True, null=True)),
                ('automatica', models.BooleanField(default=False)),
                ('notificada_vencida', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'ordering': ['vence_at'],
            },
        ),
        migrations.CreateModel(
            name='Tipificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(choices=[('venta', 'Venta (ganado)'), ('no_venta', 'No venta (perdido)')], max_length=10)),
                ('categoria', models.CharField(blank=True, help_text='Agrupa motivos en reportes (ej: "Sin interés", "Motivo económico").', max_length=80, verbose_name='Categoría')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.CharField(blank=True, max_length=300, verbose_name='Cuándo se aplica')),
                ('accion', models.CharField(blank=True, choices=[('', 'Ninguna'), ('postergar', 'Postergar: no cierra, pausa y agenda recontacto'), ('no_contactar', 'Marcar contacto como "no contactar" (bloquea mensajes y discador)'), ('dato_erroneo', 'Marcar teléfono como inválido')], default='', max_length=20)),
                ('requiere_nota', models.BooleanField(default=False, verbose_name='Nota obligatoria')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipificación',
                'verbose_name_plural': 'Tipificaciones',
                'ordering': ['resultado', 'orden', 'categoria', 'nombre'],
            },
        ),
    ]
