# Generated by Django 5.1.4 on 2026-09-24 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('telefonia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='llamada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades', to='telefonia.llamada'),
        ),
    ]
