# Generated by Django 5.1.4 on 2026-09-24 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0002_initial'),
        ('whatsapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contacto',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actividad',
            name='contacto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='crm.contacto'),
        ),
        migrations.AddField(
            model_name='embudo',
            name='agentes',
            field=models.ManyToManyField(blank=True, help_text='Reciben prospectos de este embudo y lo ven en su tablero.', related_name='embudos', to=settings.AUTH_USER_MODEL, verbose_name='Agentes habilitados'),
        ),
        migrations.AddField(
            model_name='embudo',
            name='linea_whatsapp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='embudos', to='whatsapp.lineawhatsapp', verbose_name='Línea de WhatsApp por defecto'),
        ),
        migrations.AddField(
            model_name='embudo',
            name='supervisores',
            field=models.ManyToManyField(blank=True, help_text='Reciben avisos de ventas y prospectos estancados. Vacío = todos los supervisores.', related_name='embudos_supervisados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='embudo',
            name='ultimo_asignado',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='etapa',
            name='embudo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='crm.embudo'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, related_name='contactos', to='crm.etiqueta'),
        ),
        migrations.AddField(
            model_name='historialetapa',
            name='etapa_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.etapa'),
        ),
        migrations.AddField(
            model_name='historialetapa',
            name='etapa_nueva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.etapa'),
        ),
        migrations.AddField(
            model_name='historialetapa',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='importacionlote',
            name='agente_fijo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='importacionlote',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='importacionlote',
            name='embudo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='importaciones', to='crm.embudo'),
        ),
        migrations.AddField(
            model_name='importacionlote',
            name='etapa',
            field=models.ForeignKey(blank=True, help_text='Vacío = etapa inicial del embudo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.etapa'),
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='agente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='cerrada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='contacto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oportunidades', to='crm.contacto'),
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='embudo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oportunidades', to='crm.embudo'),
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='etapa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oportunidades', to='crm.etapa'),
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidades', to='crm.importacionlote'),
        ),
        migrations.AddField(
            model_name='historialetapa',
            name='oportunidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='crm.oportunidad'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='oportunidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='crm.oportunidad'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='asignado_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tarea',
            name='contacto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='crm.contacto'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='creada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tarea',
            name='oportunidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='crm.oportunidad'),
        ),
        migrations.AddField(
            model_name='tipificacion',
            name='embudo',
            field=models.ForeignKey(blank=True, help_text='Vacío = aplica a todos los embudos.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipificaciones', to='crm.embudo'),
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='tipificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='oportunidades', to='crm.tipificacion'),
        ),
        migrations.AlterUniqueTogether(
            name='etapa',
            unique_together={('embudo', 'nombre')},
        ),
        migrations.AddConstraint(
            model_name='contacto',
            constraint=models.UniqueConstraint(condition=models.Q(('telefono', ''), _negated=True), fields=('telefono',), name='contacto_telefono_unico'),
        ),
        migrations.AddIndex(
            model_name='historialetapa',
            index=models.Index(fields=['oportunidad', '-created_at'], name='crm_histori_oportun_1b8439_idx'),
        ),
        migrations.AddIndex(
            model_name='actividad',
            index=models.Index(fields=['contacto', '-created_at'], name='crm_activid_contact_444eb0_idx'),
        ),
        migrations.AddIndex(
            model_name='actividad',
            index=models.Index(fields=['oportunidad', '-created_at'], name='crm_activid_oportun_178826_idx'),
        ),
        migrations.AddIndex(
            model_name='tarea',
            index=models.Index(fields=['asignado_a', 'estado', 'vence_at'], name='crm_tarea_asignad_d5c77a_idx'),
        ),
        migrations.AddIndex(
            model_name='oportunidad',
            index=models.Index(fields=['embudo', 'etapa', 'estado'], name='crm_oportun_embudo__ef117a_idx'),
        ),
        migrations.AddIndex(
            model_name='oportunidad',
            index=models.Index(fields=['agente', 'estado'], name='crm_oportun_agente__0879dc_idx'),
        ),
        migrations.AddIndex(
            model_name='oportunidad',
            index=models.Index(fields=['estado', 'ultima_actividad_at'], name='crm_oportun_estado_e3fe5b_idx'),
        ),
        migrations.AddIndex(
            model_name='oportunidad',
            index=models.Index(fields=['estado', 'proximo_contacto_at'], name='crm_oportun_estado_822f6c_idx'),
        ),
        migrations.AddIndex(
            model_name='oportunidad',
            index=models.Index(fields=['pendiente_asignacion', 'embudo'], name='crm_oportun_pendien_947e03_idx'),
        ),
        migrations.AddConstraint(
            model_name='oportunidad',
            constraint=models.UniqueConstraint(condition=models.Q(('estado__in', ['abierta', 'pausada'])), fields=('contacto', 'embudo'), name='una_oportunidad_activa_por_embudo'),
        ),
    ]
