# Generated by Django 5.1.4 on 2026-09-25 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_busqueda_trigram'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampoPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('slug', models.SlugField(editable=False, help_text='Clave interna: se usa en la API, en importaciones y como variable {slug} en mensajes.', max_length=60, unique=True)),
                ('tipo', models.CharField(choices=[('texto', 'Texto corto'), ('texto_largo', 'Texto largo'), ('numero', 'Número'), ('fecha', 'Fecha'), ('sino', 'Sí / No'), ('lista', 'Lista de opciones'), ('email', 'Email'), ('telefono', 'Teléfono'), ('url', 'Link (URL)')], default='texto', max_length=15)),
                ('opciones', models.JSONField(blank=True, default=list, help_text='Para "Lista de opciones".')),
                ('ayuda', models.CharField(blank=True, max_length=200, verbose_name='Texto de ayuda')),
                ('requerido', models.BooleanField(default=False, verbose_name='Obligatorio al cargar a mano')),
                ('mostrar_en_tarjeta', models.BooleanField(default=False, verbose_name='Mostrar en la tarjeta del tablero')),
                ('mostrar_en_lista', models.BooleanField(default=False, verbose_name='Mostrar como columna en listas')),
                ('filtrable', models.BooleanField(default=False, verbose_name='Permitir filtrar por este campo')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('embudo', models.ForeignKey(blank=True, help_text='Vacío = aplica a todos los contactos.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='crm.embudo')),
            ],
            options={
                'verbose_name': 'Campo personalizado',
                'verbose_name_plural': 'Campos personalizados',
                'ordering': ['orden', 'nombre'],
            },
        ),
    ]
