# Generated by Django 5.1.4 on 2026-09-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_campos_personalizados'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapa',
            name='campos_requeridos',
            field=models.JSONField(blank=True, default=list, help_text='Claves de campos fijos (email, dni, valor…) o "cp:<slug>" de campos personalizados. Se exigen al pasar a esta etapa o a cualquiera posterior (incluida Venta; no para No venta).', verbose_name='Campos obligatorios desde esta etapa'),
        ),
    ]
