# Generated by Django 5.1.4 on 2026-09-28 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_etapa_campos_requeridos'),
        ('pautas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='importacionlote',
            name='pauta',
            field=models.ForeignKey(blank=True, help_text='Pauta de toda la base (si no viene una columna de origen por fila).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pautas.pauta'),
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='origen_pauta',
            field=models.CharField(blank=True, db_index=True, help_text='Texto de origen tal cual llegó (formulario, utm_campaign…).', max_length=200, verbose_name='Origen (pauta)'),
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='pauta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidades', to='pautas.pauta'),
        ),
        migrations.AddIndex(
            model_name='oportunidad',
            index=models.Index(fields=['pauta', 'created_at'], name='crm_oportun_pauta_i_7af005_idx'),
        ),
    ]
