# Generated by Django 5.1.4 on 2026-09-29 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_importacionlote_pauta_oportunidad_origen_pauta_and_more'),
        ('pautas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='embudo',
            name='asignar_entre',
            field=models.CharField(choices=[('todos', 'Todos los agentes habilitados'), ('conectados', 'Solo los agentes conectados en ese momento')], default='todos', max_length=12, verbose_name='Repartir entre'),
        ),
        migrations.AddField(
            model_name='embudo',
            name='sin_conectados',
            field=models.CharField(choices=[('encolar', 'Esperar y asignarlo apenas alguien se conecte'), ('todos', 'Asignarlo igual entre todos')], default='encolar', max_length=10, verbose_name='Si no hay nadie conectado'),
        ),
        migrations.CreateModel(
            name='ReglaAsignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('canales', models.JSONField(blank=True, default=list, help_text='Vacío = cualquier canal.', verbose_name='Canal de ingreso')),
                ('textos_origen', models.JSONField(blank=True, default=list, help_text='Vacío = cualquier origen.', verbose_name='El origen contiene')),
                ('accion', models.CharField(choices=[('agentes', 'Asignar solo a estos agentes'), ('sin_asignar', 'No asignar (queda para asignación manual)')], default='agentes', max_length=12)),
                ('asignar_entre', models.CharField(choices=[('embudo', 'Como el embudo'), ('todos', 'Todos los agentes habilitados'), ('conectados', 'Solo los agentes conectados en ese momento')], default='embudo', max_length=12, verbose_name='Repartir entre')),
                ('si_no_hay', models.CharField(choices=[('encolar', 'Esperar a que uno de ellos se conecte / esté disponible'), ('todos', 'Asignar igual entre ellos aunque no estén conectados'), ('embudo', 'Usar la asignación general del embudo')], default='encolar', max_length=10, verbose_name='Si ninguno de ellos puede recibir')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agentes', models.ManyToManyField(blank=True, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('embudo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas_asignacion', to='crm.embudo')),
                ('pautas', models.ManyToManyField(blank=True, help_text='Vacío = cualquier pauta.', related_name='reglas_asignacion', to='pautas.pauta')),
                ('ultimo_asignado', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Regla de asignación',
                'verbose_name_plural': 'Reglas de asignación',
                'ordering': ['embudo', 'orden', 'pk'],
            },
        ),
    ]
