# Generated by Django 5.1.4 on 2026-09-29 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_asignacion_reglas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='tipo',
            field=models.CharField(choices=[('nota', 'Nota'), ('llamada', 'Llamada'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('etapa', 'Cambio de etapa'), ('asignacion', 'Asignación'), ('intento', 'Intento de contacto'), ('tarea', 'Tarea'), ('pausa', 'Pausa / reactivación'), ('cierre', 'Cierre'), ('reingreso', 'Reingreso del dato'), ('sistema', 'Sistema'), ('cambio', 'Cambio de datos')], max_length=15),
        ),
    ]
