# Generated by Django 5.1.4 on 2026-10-03 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_actividad_cambio'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunidad',
            name='embudo_previo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.embudo'),
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='etapa_previa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.etapa'),
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='oportunidad_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivadas', to='crm.oportunidad'),
        ),
    ]
