# Generated by Django 5.1.4 on 2026-10-06 22:00

from django.db import migrations, models
from django.db.models import Count


def completar_ingresos(apps, schema_editor):
    Actividad = apps.get_model('crm', 'Actividad')
    Oportunidad = apps.get_model('crm', 'Oportunidad')
    conteos = (Actividad.objects.filter(tipo='reingreso', oportunidad__isnull=False)
               .values_list('oportunidad').annotate(n=Count('pk')))
    for op_id, n in conteos.iterator():
        Oportunidad.objects.filter(pk=op_id).update(ingresos=1 + n)


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_oportunidad_embudo_previo_oportunidad_etapa_previa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunidad',
            name='ingresos',
            field=models.PositiveIntegerField(default=1, help_text='Veces que la persona entró por esta oportunidad (primer ingreso + reingresos).'),
        ),
        migrations.RunPython(completar_ingresos, migrations.RunPython.noop),
    ]
