# Generated by Django 5.1.4 on 2026-10-06 22:07

from django.db import migrations, models
from django.db.models import Min


def completar_primer_contacto(apps, schema_editor):
    Actividad = apps.get_model('crm', 'Actividad')
    Oportunidad = apps.get_model('crm', 'Oportunidad')
    primeras = (Actividad.objects.filter(oportunidad__isnull=False, usuario__isnull=False,
                                         tipo__in=['intento', 'llamada', 'whatsapp', 'etapa', 'cierre'])
                .values_list('oportunidad').annotate(t=Min('created_at')))
    for op_id, t in primeras.iterator():
        Oportunidad.objects.filter(pk=op_id, primer_contacto_at__isnull=True).update(primer_contacto_at=t)


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_ingresos'),
    ]

    operations = [
        migrations.AddField(
            model_name='embudo',
            name='sla_accion',
            field=models.CharField(choices=[('avisar', 'Avisar al vendedor y a supervisión'), ('reasignar', 'Avisar y reasignar a otro vendedor')], default='avisar', max_length=10, verbose_name='Si se vence el SLA'),
        ),
        migrations.AddField(
            model_name='embudo',
            name='sla_max_reasignaciones',
            field=models.PositiveSmallIntegerField(default=1, help_text='Veces por lead (evita que dé vueltas).', verbose_name='Reasignar como máximo'),
        ),
        migrations.AddField(
            model_name='embudo',
            name='sla_minutos',
            field=models.PositiveIntegerField(default=0, help_text='Tiempo máximo desde que se asigna el lead hasta la primera gestión (llamada, mensaje o intento). 0 = sin SLA.', verbose_name='SLA de primer contacto (minutos)'),
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='primer_contacto_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Primera gestión del vendedor: llamada, mensaje o intento.', null=True),
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='reasignaciones_sla',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='sla_alerta_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.RunPython(completar_primer_contacto, migrations.RunPython.noop),
    ]
