# Generated by Django 5.1.4 on 2026-10-06 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_alter_actividad_tipo'),
        ('pautas', '0002_whatsapp_anuncios_palabras'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunidad',
            name='puntaje',
            field=models.IntegerField(db_index=True, default=0, help_text='Lead scoring según las reglas configuradas.'),
        ),
        migrations.CreateModel(
            name='ReglaPuntaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condicion', models.CharField(choices=[('respondio', 'El cliente respondió alguna vez (WhatsApp, SMS o llamada atendida)'), ('pauta', 'Vino de la pauta…'), ('canal', 'Entró por el canal…'), ('origen_contiene', 'El origen contiene el texto…'), ('campo', 'El campo … tiene el valor … (vacío = tiene dato)'), ('tiene_email', 'Tiene email'), ('etapa', 'Está en la etapa…'), ('ingresos_min', 'Ingresó al menos N veces'), ('intentos_min', 'Lleva al menos N intentos sin contacto efectivo'), ('sin_actividad_dias', 'Lleva al menos N días sin actividad')], max_length=20)),
                ('campo', models.CharField(blank=True, help_text='Clave del campo (ej. localidad, o la de un campo personalizado).', max_length=80)),
                ('valor', models.CharField(blank=True, max_length=200)),
                ('numero', models.PositiveIntegerField(default=0)),
                ('puntos', models.IntegerField(help_text='Positivo suma, negativo resta.')),
                ('activa', models.BooleanField(default=True)),
                ('embudo', models.ForeignKey(blank=True, help_text='Vacío = todos los embudos.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reglas_puntaje', to='crm.embudo')),
                ('etapa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='crm.etapa')),
                ('pauta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pautas.pauta')),
            ],
            options={
                'ordering': ['embudo__nombre', '-puntos', 'pk'],
            },
        ),
    ]
