# Generated by Django 5.1.4 on 2026-10-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_puntaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='no_email',
            field=models.BooleanField(default=False, help_text='Se dio de baja desde un email: no recibe difusiones ni emails automáticos.', verbose_name='No recibir emails masivos'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='no_email_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
