# Generated by Django 5.1.4 on 2026-10-09 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_contacto_no_email_contacto_no_email_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='embudo',
            name='etiqueta_venta',
            field=models.ForeignKey(blank=True, help_text='Ej. "Socio": se le pone al contacto al ganar.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.etiqueta', verbose_name='Etiqueta al cerrar como venta'),
        ),
        migrations.AddField(
            model_name='embudo',
            name='exigir_resultado',
            field=models.BooleanField(default=True, help_text='Al cortar se abre "Resultado de la gestión" y no se puede seguir (ni recibir la próxima llamada del discador) sin cargarlo.', verbose_name='Pedir el resultado de la gestión al terminar cada llamada atendida'),
        ),
        migrations.AddField(
            model_name='embudo',
            name='socios_a',
            field=models.CharField(blank=True, choices=[('vendedor', 'Al vendedor que hizo la venta'), ('usuario', 'A un usuario fijo (postventa / experiencia del socio)'), ('', 'A nadie (quedan sin asignar)')], default='vendedor', max_length=10, verbose_name='Si escribe o llama alguien que ya es cliente, va'),
        ),
        migrations.AddField(
            model_name='embudo',
            name='socios_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de postventa'),
        ),
        migrations.AddField(
            model_name='embudo',
            name='vence_accion',
            field=models.CharField(choices=[('reasignar', 'Reasignarla a otro vendedor (reparto parejo)'), ('liberar', 'Dejarla sin asignar (la reparte supervisión)'), ('avisar', 'Solo avisar al vendedor y a supervisión')], default='reasignar', max_length=10, verbose_name='Al vencer'),
        ),
        migrations.AddField(
            model_name='embudo',
            name='vence_dias',
            field=models.PositiveSmallIntegerField(default=0, help_text='Días desde que se le asignó al vendedor sin cerrarse (venta / no venta). 0 = no vence.', verbose_name='La ficha vence a los (días)'),
        ),
        migrations.AddField(
            model_name='embudo',
            name='vence_hasta_etapa',
            field=models.ForeignKey(blank=True, help_text='Desde esta etapa en adelante la ficha queda siempre del vendedor (ej. Preventa).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.etapa', verbose_name='No vence desde la etapa'),
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='prioridad_motivo',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='prioritaria',
            field=models.BooleanField(db_index=True, default=False, help_text='Marcada como prioridad (ej. reingresó): aparece primero.'),
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='vencida_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='Cuándo se procesó el vencimiento de la ficha (se limpia al reasignar).', null=True),
        ),
        migrations.CreateModel(
            name='ResultadoGestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('contactado', models.BooleanField(default=True, help_text='Cuenta como contacto efectivo en los reportes.', verbose_name='Habló con el cliente')),
                ('pide_fecha', models.BooleanField(default=False, help_text='Crea la tarea de rellamado para esa fecha.', verbose_name='Pide fecha para volver a llamar')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('embudo', models.ForeignKey(blank=True, help_text='Vacío = aplica a todos los embudos.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='crm.embudo')),
                ('mover_a', models.ForeignKey(blank=True, help_text='Opcional. Solo etapas abiertas.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.etapa', verbose_name='Mover la tarjeta a')),
            ],
            options={
                'verbose_name': 'Resultado de gestión',
                'verbose_name_plural': 'Resultados de gestión',
                'ordering': ['orden', 'nombre'],
            },
        ),
    ]
