# Generated by Django 5.1.4 on 2026-10-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_embudo_etiqueta_venta_embudo_exigir_resultado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='embudo',
            name='clientes_de_otros',
            field=models.BooleanField(default=False, help_text='Desmarcado: si el número ya tiene una venta en cualquier embudo, no se abre tarjeta ni se reparte (queda como reingreso del cliente). Marcalo en embudos de upgrade / venta cruzada.', verbose_name='Abrir tarjeta aunque ya sea cliente de otro embudo'),
        ),
    ]
