# Generated by Django 5.1.4 on 2026-10-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_embudo_clientes_de_otros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campopersonalizado',
            name='tipo',
            field=models.CharField(choices=[('texto', 'Texto corto'), ('texto_largo', 'Texto largo'), ('numero', 'Número'), ('fecha', 'Fecha'), ('sino', 'Sí / No'), ('lista', 'Lista de opciones'), ('email', 'Email'), ('telefono', 'Teléfono'), ('url', 'Link (URL)'), ('archivo', 'Archivo / documento (ej. recibo de sueldo, DNI)')], default='texto', max_length=15),
        ),
    ]
