# Generated by Django 5.1.4 on 2026-09-28 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0006_etapa_campos_requeridos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pauta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('plataforma', models.CharField(choices=[('meta', 'Meta (Instagram / Facebook)'), ('google', 'Google Ads'), ('tiktok', 'TikTok'), ('email', 'Email marketing'), ('web', 'Sitio web / SEO'), ('offline', 'Offline / eventos'), ('otra', 'Otra')], default='meta', max_length=15)),
                ('claves', models.JSONField(blank=True, default=list, help_text='Otros textos de origen que corresponden a esta pauta (utm_campaign, nombre del anuncio…). No distingue mayúsculas, acentos, guiones ni guiones bajos.', verbose_name='También llega como')),
                ('inicio', models.DateField(blank=True, null=True)),
                ('fin', models.DateField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('embudo', models.ForeignKey(blank=True, help_text='Opcional: solo informativo / filtro.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pautas', to='crm.embudo')),
            ],
            options={
                'ordering': ['-activa', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='InversionPauta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Día o primer día del período al que corresponde el gasto.')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('nota', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cargada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pauta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inversiones', to='pautas.pauta')),
            ],
            options={
                'ordering': ['-fecha', '-pk'],
                'indexes': [models.Index(fields=['pauta', 'fecha'], name='pautas_inve_pauta_i_8e82ed_idx')],
            },
        ),
    ]
