# Generated by Django 5.1.4 on 2026-10-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pautas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pauta',
            name='anuncio_ids',
            field=models.JSONField(blank=True, default=list, help_text='Para chats de WhatsApp que llegan desde un anuncio "clic para WhatsApp": Meta manda el ID del anuncio en el primer mensaje.', verbose_name='IDs de anuncio (Meta)'),
        ),
        migrations.AddField(
            model_name='pauta',
            name='palabras_clave',
            field=models.JSONField(blank=True, default=list, help_text='Si el chat no trae datos del anuncio, se busca alguno de estos textos en el primer mensaje (un código como #IG-SEP o una frase del mensaje precargado del link).', verbose_name='Palabras clave en el primer mensaje de WhatsApp'),
        ),
    ]
